function viewDiv1(){
    document.getElementById("div2").style.display = "none";
    document.getElementById("div3").style.display = "none";
    document.getElementById("div4").style.display = "none";
    document.getElementById("div5").style.display = "none";
    document.getElementById("div6").style.display = "none";
    document.getElementById("div7").style.display = "none";
    document.getElementById("div8").style.display = "none";
    document.getElementById("div9").style.display = "none";
    document.getElementById("div10").style.display = "none";
    document.getElementById("div1").style.display = "block";
};
function viewDiv2(){
    document.getElementById("div1").style.display = "none";
    document.getElementById("div3").style.display = "none";
    document.getElementById("div4").style.display = "none";
    document.getElementById("div5").style.display = "none";
    document.getElementById("div6").style.display = "none";
    document.getElementById("div7").style.display = "none";
    document.getElementById("div8").style.display = "none";
    document.getElementById("div9").style.display = "none";
    document.getElementById("div10").style.display = "none";
    document.getElementById("div2").style.display = "block";
};
function viewDiv3(){
    document.getElementById("div1").style.display = "none";
    document.getElementById("div2").style.display = "none";
    document.getElementById("div4").style.display = "none";
    document.getElementById("div5").style.display = "none";
    document.getElementById("div6").style.display = "none";
    document.getElementById("div7").style.display = "none";
    document.getElementById("div8").style.display = "none";
    document.getElementById("div9").style.display = "none";
    document.getElementById("div10").style.display = "none";
    document.getElementById("div3").style.display = "block";
};
function viewDiv4(){
    document.getElementById("div1").style.display = "none";
    document.getElementById("div2").style.display = "none";
    document.getElementById("div3").style.display = "none";
    document.getElementById("div5").style.display = "none";
    document.getElementById("div6").style.display = "none";
    document.getElementById("div7").style.display = "none";
    document.getElementById("div8").style.display = "none";
    document.getElementById("div9").style.display = "none";
    document.getElementById("div10").style.display = "none";
    document.getElementById("div4").style.display = "block";
};
function viewDiv5(){
    document.getElementById("div1").style.display = "none";
    document.getElementById("div2").style.display = "none";
    document.getElementById("div3").style.display = "none";
    document.getElementById("div4").style.display = "none";
    document.getElementById("div6").style.display = "none";
    document.getElementById("div7").style.display = "none";
    document.getElementById("div8").style.display = "none";
    document.getElementById("div9").style.display = "none";
    document.getElementById("div10").style.display = "none";
    document.getElementById("div5").style.display = "block";
};
function viewDiv6(){
    document.getElementById("div1").style.display = "none";
    document.getElementById("div2").style.display = "none";
    document.getElementById("div3").style.display = "none";
    document.getElementById("div4").style.display = "none";
    document.getElementById("div5").style.display = "none";
    document.getElementById("div7").style.display = "none";
    document.getElementById("div8").style.display = "none";
    document.getElementById("div9").style.display = "none";
    document.getElementById("div10").style.display = "none";
    document.getElementById("div6").style.display = "block";
};
function viewDiv7(){
    document.getElementById("div1").style.display = "none";
    document.getElementById("div2").style.display = "none";
    document.getElementById("div3").style.display = "none";
    document.getElementById("div4").style.display = "none";
    document.getElementById("div5").style.display = "none";
    document.getElementById("div6").style.display = "none";
    document.getElementById("div8").style.display = "none";
    document.getElementById("div9").style.display = "none";
    document.getElementById("div10").style.display = "none";
    document.getElementById("div7").style.display = "block";
};
function viewDiv8(){
    document.getElementById("div1").style.display = "none";
    document.getElementById("div2").style.display = "none";
    document.getElementById("div3").style.display = "none";
    document.getElementById("div4").style.display = "none";
    document.getElementById("div5").style.display = "none";
    document.getElementById("div6").style.display = "none";
    document.getElementById("div7").style.display = "none";
    document.getElementById("div9").style.display = "none";
    document.getElementById("div10").style.display = "none";
    document.getElementById("div8").style.display = "block";
};
function viewDiv9(){
    document.getElementById("div1").style.display = "none";
    document.getElementById("div2").style.display = "none";
    document.getElementById("div3").style.display = "none";
    document.getElementById("div4").style.display = "none";
    document.getElementById("div5").style.display = "none";
    document.getElementById("div6").style.display = "none";
    document.getElementById("div7").style.display = "none";
    document.getElementById("div8").style.display = "none";
    document.getElementById("div10").style.display = "none";
    document.getElementById("div9").style.display = "block";
};
function viewDiv10(){
    document.getElementById("div1").style.display = "none";
    document.getElementById("div2").style.display = "none";
    document.getElementById("div3").style.display = "none";
    document.getElementById("div4").style.display = "none";
    document.getElementById("div5").style.display = "none";
    document.getElementById("div6").style.display = "none";
    document.getElementById("div7").style.display = "none";
    document.getElementById("div8").style.display = "none";
    document.getElementById("div9").style.display = "none";
    document.getElementById("div10").style.display = "block";
};